package com.ysd.springboot.entity;

import java.io.Serializable;

public class Readrooms implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column readrooms.reaId
     *
     * @mbggenerated
     */
    private Integer reaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column readrooms.reaName
     *
     * @mbggenerated
     */
    private String reaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column readrooms.reaRemark
     *
     * @mbggenerated
     */
    private String rearemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table readrooms
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column readrooms.reaId
     *
     * @return the value of readrooms.reaId
     *
     * @mbggenerated
     */
    public Integer getReaid() {
        return reaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column readrooms.reaId
     *
     * @param reaid the value for readrooms.reaId
     *
     * @mbggenerated
     */
    public void setReaid(Integer reaid) {
        this.reaid = reaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column readrooms.reaName
     *
     * @return the value of readrooms.reaName
     *
     * @mbggenerated
     */
    public String getReaname() {
        return reaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column readrooms.reaName
     *
     * @param reaname the value for readrooms.reaName
     *
     * @mbggenerated
     */
    public void setReaname(String reaname) {
        this.reaname = reaname == null ? null : reaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column readrooms.reaRemark
     *
     * @return the value of readrooms.reaRemark
     *
     * @mbggenerated
     */
    public String getRearemark() {
        return rearemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column readrooms.reaRemark
     *
     * @param rearemark the value for readrooms.reaRemark
     *
     * @mbggenerated
     */
    public void setRearemark(String rearemark) {
        this.rearemark = rearemark == null ? null : rearemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readrooms
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", reaid=").append(reaid);
        sb.append(", reaname=").append(reaname);
        sb.append(", rearemark=").append(rearemark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}