package com.ysd.springboot.entity;

import java.io.Serializable;

public class Sections implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sections.secId
     *
     * @mbggenerated
     */
    private Integer secid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sections.secName
     *
     * @mbggenerated
     */
    private String secname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sections.secRemark
     *
     * @mbggenerated
     */
    private String secremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sections
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sections.secId
     *
     * @return the value of sections.secId
     *
     * @mbggenerated
     */
    public Integer getSecid() {
        return secid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sections.secId
     *
     * @param secid the value for sections.secId
     *
     * @mbggenerated
     */
    public void setSecid(Integer secid) {
        this.secid = secid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sections.secName
     *
     * @return the value of sections.secName
     *
     * @mbggenerated
     */
    public String getSecname() {
        return secname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sections.secName
     *
     * @param secname the value for sections.secName
     *
     * @mbggenerated
     */
    public void setSecname(String secname) {
        this.secname = secname == null ? null : secname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sections.secRemark
     *
     * @return the value of sections.secRemark
     *
     * @mbggenerated
     */
    public String getSecremark() {
        return secremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sections.secRemark
     *
     * @param secremark the value for sections.secRemark
     *
     * @mbggenerated
     */
    public void setSecremark(String secremark) {
        this.secremark = secremark == null ? null : secremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sections
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", secid=").append(secid);
        sb.append(", secname=").append(secname);
        sb.append(", secremark=").append(secremark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}