package com.ysd.springboot.entity;

import java.io.Serializable;

public class Statistics implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics.staId
     *
     * @mbggenerated
     */
    private Integer staid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics.readroomId
     *
     * @mbggenerated
     */
    private Integer readroomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics.peopleNums
     *
     * @mbggenerated
     */
    private Integer peoplenums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics.year
     *
     * @mbggenerated
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics.month
     *
     * @mbggenerated
     */
    private String month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statistics.day
     *
     * @mbggenerated
     */
    private String day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table statistics
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics.staId
     *
     * @return the value of statistics.staId
     *
     * @mbggenerated
     */
    public Integer getStaid() {
        return staid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics.staId
     *
     * @param staid the value for statistics.staId
     *
     * @mbggenerated
     */
    public void setStaid(Integer staid) {
        this.staid = staid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics.readroomId
     *
     * @return the value of statistics.readroomId
     *
     * @mbggenerated
     */
    public Integer getReadroomid() {
        return readroomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics.readroomId
     *
     * @param readroomid the value for statistics.readroomId
     *
     * @mbggenerated
     */
    public void setReadroomid(Integer readroomid) {
        this.readroomid = readroomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics.peopleNums
     *
     * @return the value of statistics.peopleNums
     *
     * @mbggenerated
     */
    public Integer getPeoplenums() {
        return peoplenums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics.peopleNums
     *
     * @param peoplenums the value for statistics.peopleNums
     *
     * @mbggenerated
     */
    public void setPeoplenums(Integer peoplenums) {
        this.peoplenums = peoplenums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics.year
     *
     * @return the value of statistics.year
     *
     * @mbggenerated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics.year
     *
     * @param year the value for statistics.year
     *
     * @mbggenerated
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics.month
     *
     * @return the value of statistics.month
     *
     * @mbggenerated
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics.month
     *
     * @param month the value for statistics.month
     *
     * @mbggenerated
     */
    public void setMonth(String month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statistics.day
     *
     * @return the value of statistics.day
     *
     * @mbggenerated
     */
    public String getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statistics.day
     *
     * @param day the value for statistics.day
     *
     * @mbggenerated
     */
    public void setDay(String day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", staid=").append(staid);
        sb.append(", readroomid=").append(readroomid);
        sb.append(", peoplenums=").append(peoplenums);
        sb.append(", year=").append(year);
        sb.append(", month=").append(month);
        sb.append(", day=").append(day);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}