package com.ysd.springboot.entity;

import java.io.Serializable;
import java.util.Date;

public class Students implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.stuId
     *
     * @mbggenerated
     */
    private Integer stuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.stuCardno
     *
     * @mbggenerated
     */
    private String stucardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.stuName
     *
     * @mbggenerated
     */
    private String stuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.stuSex
     *
     * @mbggenerated
     */
    private String stusex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.membershipId
     *
     * @mbggenerated
     */
    private Integer membershipid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.stuStatus
     *
     * @mbggenerated
     */
    private Integer stustatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.stuRemark
     *
     * @mbggenerated
     */
    private String sturemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.stuNo
     *
     * @mbggenerated
     */
    private String stuno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table students
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.stuId
     *
     * @return the value of students.stuId
     *
     * @mbggenerated
     */
    public Integer getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.stuId
     *
     * @param stuid the value for students.stuId
     *
     * @mbggenerated
     */
    public void setStuid(Integer stuid) {
        this.stuid = stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.stuCardno
     *
     * @return the value of students.stuCardno
     *
     * @mbggenerated
     */
    public String getStucardno() {
        return stucardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.stuCardno
     *
     * @param stucardno the value for students.stuCardno
     *
     * @mbggenerated
     */
    public void setStucardno(String stucardno) {
        this.stucardno = stucardno == null ? null : stucardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.stuName
     *
     * @return the value of students.stuName
     *
     * @mbggenerated
     */
    public String getStuname() {
        return stuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.stuName
     *
     * @param stuname the value for students.stuName
     *
     * @mbggenerated
     */
    public void setStuname(String stuname) {
        this.stuname = stuname == null ? null : stuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.stuSex
     *
     * @return the value of students.stuSex
     *
     * @mbggenerated
     */
    public String getStusex() {
        return stusex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.stuSex
     *
     * @param stusex the value for students.stuSex
     *
     * @mbggenerated
     */
    public void setStusex(String stusex) {
        this.stusex = stusex == null ? null : stusex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.membershipId
     *
     * @return the value of students.membershipId
     *
     * @mbggenerated
     */
    public Integer getMembershipid() {
        return membershipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.membershipId
     *
     * @param membershipid the value for students.membershipId
     *
     * @mbggenerated
     */
    public void setMembershipid(Integer membershipid) {
        this.membershipid = membershipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.stuStatus
     *
     * @return the value of students.stuStatus
     *
     * @mbggenerated
     */
    public Integer getStustatus() {
        return stustatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.stuStatus
     *
     * @param stustatus the value for students.stuStatus
     *
     * @mbggenerated
     */
    public void setStustatus(Integer stustatus) {
        this.stustatus = stustatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.stuRemark
     *
     * @return the value of students.stuRemark
     *
     * @mbggenerated
     */
    public String getSturemark() {
        return sturemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.stuRemark
     *
     * @param sturemark the value for students.stuRemark
     *
     * @mbggenerated
     */
    public void setSturemark(String sturemark) {
        this.sturemark = sturemark == null ? null : sturemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.stuNo
     *
     * @return the value of students.stuNo
     *
     * @mbggenerated
     */
    public String getStuno() {
        return stuno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.stuNo
     *
     * @param stuno the value for students.stuNo
     *
     * @mbggenerated
     */
    public void setStuno(String stuno) {
        this.stuno = stuno == null ? null : stuno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", stuid=").append(stuid);
        sb.append(", stucardno=").append(stucardno);
        sb.append(", stuname=").append(stuname);
        sb.append(", stusex=").append(stusex);
        sb.append(", membershipid=").append(membershipid);
        sb.append(", stustatus=").append(stustatus);
        sb.append(", sturemark=").append(sturemark);
        sb.append(", stuno=").append(stuno);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

}