package com.ysd.springboot.mapper.dao;

import com.ysd.springboot.entity.Consumelogs;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ConsumelogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumelogs
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer conid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumelogs
     *
     * @mbggenerated
     */
    int insert(Consumelogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumelogs
     *
     * @mbggenerated
     */
    Consumelogs selectByPrimaryKey(Integer conid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumelogs
     *
     * @mbggenerated
     */
    List<Consumelogs> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumelogs
     *
     * @mbggenerated
     */
    int updateByCardno(Consumelogs consumelogs);
    
    Consumelogs selectByCardno(String cardno);
    
    List<Consumelogs> getPeopleByReaid(Integer reaid);
}