package com.ysd.springboot.mapper.dao;

import com.ysd.springboot.entity.Readrooms;
import java.util.List;

public interface ReadroomsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readrooms
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer reaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readrooms
     *
     * @mbggenerated
     */
    int insert(Readrooms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readrooms
     *
     * @mbggenerated
     */
    Readrooms selectByPrimaryKey(Integer reaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readrooms
     *
     * @mbggenerated
     */
    List<Readrooms> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readrooms
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Readrooms record);
    
}