package com.ysd.springboot.mapper.dao;

import com.ysd.springboot.entity.Statistics;
import java.util.List;
import java.util.Map;

public interface StatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer staid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbggenerated
     */
    int insert(Statistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbggenerated
     */
    Statistics selectByPrimaryKey(Integer staid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbggenerated
     */
    List<Statistics> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table statistics
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Statistics record);
    /**
     * 通过阅览室id获取日志表中该阅览室的进入人数
     * @param reaid
     * @return
     */
    int getReadroomsCount(Integer reaid);
}