package com.ysd.springboot.mapper.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ysd.springboot.entity.Students;

public interface StudentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer stuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbggenerated
     */
    int insert(Students record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbggenerated
     */
    List<Students> selectStudentByName(@Param("name")String name,@Param("startIndex")Integer startIndex,@Param("rows")Integer rows);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbggenerated
     */
    List<Students> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(@Param("name")String name,@Param("sex")String sex ,@Param("id")Integer id);
    
    int insertExcel(Students student);
    
    Students getStudentById(int stuid);
    
    int updateStatusByCardno(@Param("status")Integer status,@Param("cardno")String cardno);
    
}